application: poznanopen09
version: dev
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

#- url: /admin/.*
#  script: common/appenginepatch/main_admin.py
#  login: admin

- url: /.*
  script: common/appenginepatch/main.py
